import { l } from '../../i18n';

/** Keep both locales current whenever a gesture, shortcut or behavior changes. */
export function installHelp(button: HTMLButtonElement): void {
  const dialog = document.createElement('dialog');
  dialog.className = 'help-dialog';
  dialog.setAttribute('aria-labelledby', 'help-title');
  dialog.innerHTML = l(`
    <header class="help-heading"><div><span class="eyebrow">JV STUDIO · GUÍA DE USO</span><h2 id="help-title">Ayuda</h2></div><button type="button" data-close-help autofocus aria-label="Cerrar ayuda">Cerrar · Esc</button></header>
    <div class="help-content">
      <section class="help-notice"><h3>Antes de empezar</h3><p>Al entrar encontrarás <strong>First Pattern</strong>, una idea musical de dos compases ya seleccionada y abierta en la vista combinada. Puedes escucharla, modificar sus notas, moverla o borrarla para empezar desde cero.</p><p>Los cambios duran mientras mantengas esta página abierta. <strong>Recargar o cerrar reinicia el proyecto demo.</strong> Guardar, abrir y exportar todavía no están disponibles.</p></section>
      <section><h3>Reproducir tu arreglo</h3><p>Pulsa <strong>Play</strong> para activar el audio. <strong>Pausa</strong> conserva la posición y Play reanuda desde ella; <strong>Stop</strong> detiene y vuelve al inicio. En el espacio de trabajo, <strong>Espacio</strong> alterna entre Play y Pausa, excepto mientras escribes o usas un control. Puedes cambiar el tempo entre 40 y 240 BPM mientras suena.</p><p>El proyecto completo se repite en bucle. Cada clip suena una vez donde está colocado; duplica un clip para repetir su patrón. Crear, mover, duplicar o borrar detiene la reproducción.</p></section>
      <section><h3>Pistas y clips</h3><ul><li>Pulsa <strong>＋</strong> junto a PISTAS para añadir una pista.</li><li>Selecciona una pista o clip para ver sus propiedades.</li><li><strong>Nuevo clip</strong> crea uno de un compás en el primer hueco libre. También puedes hacer doble clic en un hueco.</li><li>Arrastra horizontalmente un clip para moverlo con ajuste a compás. Una posición ocupada se marca en rojo y se rechaza.</li><li><strong>Duplicar</strong> copia el clip y sus notas; <strong>Borrar</strong> elimina el seleccionado. Todavía no hay Deshacer.</li></ul><p>Los clips deben caber dentro del proyecto y no pueden solaparse en una misma pista.</p></section>
      <section><h3>Instrumentos y mezcla</h3><p>Selecciona una pista para abrir su mezclador. Sus controles siguen visibles aunque también haya un clip seleccionado.</p><ul><li><strong>Instrumento</strong> elige uno de los nueve preajustes sintetizados en el navegador, sin muestras ni grabaciones externas.</li><li><strong>Volumen</strong> regula de 0 a 100%. <strong>Panorámica</strong> desplaza entre izquierda (I), centro (C) y derecha (D).</li><li><strong>Silencio</strong> silencia esa pista. <strong>Solo</strong> excluye las que no estén en Solo; puede haber varias pistas en Solo.</li><li>Todos estos cambios se aplican mientras el transporte está sonando, sin volver al inicio.</li></ul><p>La audición del Piano Roll mantiene instrumento, volumen y panorámica, pero evita Silencio/Solo para que puedas afinar una pista mientras la editas.</p></section>
      <section><h3>Combinaciones de teclas</h3><p>Selecciona un clip en el Arranger. No se aplican mientras escribes en un campo.</p><dl class="help-shortcuts"><div><dt><kbd>Espacio</kbd></dt><dd>Alternar Play y Pausa en el espacio de trabajo.</dd></div><div><dt><kbd>←</kbd> / <kbd>→</kbd></dt><dd>Mover el clip un compás.</dd></div><div><dt><kbd>Ctrl</kbd> + <kbd>D</kbd></dt><dd>Duplicar el clip. En Mac: Cmd + D.</dd></div><div><dt><kbd>Supr</kbd> / <kbd>Backspace</kbd></dt><dd>Borrar el clip seleccionado.</dd></div><div><dt><kbd>Esc</kbd></dt><dd>Cancelar un arrastre o cerrar esta ayuda.</dd></div><div><dt><kbd>Tab</kbd></dt><dd>Recorrer controles; Enter activa el control enfocado.</dd></div></dl></section>
      <section><h3>Piano Roll: componer dentro de un clip</h3><p>La vista combinada se abre por defecto con <strong>First Pattern</strong>. Los controles contiguos <strong>Arranger</strong> y <strong>Piano Roll</strong> indican qué panel tiene el foco sin ocultar el otro. Si cierras el editor, haz doble clic en un clip o selecciónalo y pulsa <strong>Piano Roll</strong> para volver a abrirlo. Se acopla bajo el Arranger y ambos permanecen visibles con el transporte superior. Arrastra el divisor horizontal para repartir su altura; el divisor vertical entre Pistas y Arranger cambia el ancho. Ambos también responden a las flechas cuando tienen el foco y conservan la posición durante la sesión. <strong>Ampliar</strong> dedica el espacio de trabajo al editor; <strong>Restaurar</strong> vuelve a la vista combinada y <strong>Cerrar</strong> lo oculta.</p><ul><li>El teclado muestra solo los Do de cada octava (C1, C2…). Sus teclas negras continúan por el grid con un sombreado sutil. Pulsa cualquier tecla para escucharla.</li><li><strong>Dibujar</strong> crea notas; <strong>Seleccionar</strong> permite moverlas y cambiar su duración desde el borde derecho; <strong>Borrar</strong> las elimina.</li><li>Al arrastrar verticalmente una nota suena cada nuevo semitono alcanzado. El movimiento horizontal y el cambio de duración no repiten la escucha.</li><li><strong>Ajuste</strong> ofrece 1/4–1/32. Zoom cambia la escala horizontal. El formulario edita MIDI, inicio, duración y velocidad.</li><li>Con una nota enfocada: flechas horizontales mueven un paso de ajuste, flechas verticales un semitono y Supr/Backspace borra.</li></ul><p>Editar notas detiene la reproducción; pulsa Play para escuchar el resultado.</p></section>
      <section><h3>Qué puedes probar ahora</h3><p>Pulsa Play para escuchar los dos compases de First Pattern y cambia alguna nota mientras mantienes el clip a la vista en el Arranger. Prueba Ampliar, Restaurar y Cerrar; después crea una segunda pista y mezcla instrumentos distintos.</p></section>
    </div>
  `, `
    <header class="help-heading"><div><span class="eyebrow">JV STUDIO · USER GUIDE</span><h2 id="help-title">Help</h2></div><button type="button" data-close-help autofocus aria-label="Close help">Close · Esc</button></header>
    <div class="help-content">
      <section class="help-notice"><h3>Before you begin</h3><p>You begin with <strong>First Pattern</strong>, a selected two-bar musical idea already open in the combined view. Listen to it, edit its notes, move it, or delete it to start from scratch.</p><p>Changes last only while this page stays open. <strong>Reloading or closing resets the demo project.</strong> Open, Save and Export are not available yet.</p></section>
      <section><h3>Play your arrangement</h3><p>Press <strong>Play</strong> to start audio. <strong>Pause</strong> preserves the position and Play resumes from it; <strong>Stop</strong> stops and returns to the beginning. In the workspace, <strong>Space</strong> toggles Play and Pause except while typing or using a control. Tempo can change from 40 to 240 BPM during playback.</p><p>The whole project loops. Each clip plays once at its position; duplicate a clip to repeat its pattern. Creating, moving, duplicating or deleting stops playback.</p></section>
      <section><h3>Tracks and clips</h3><ul><li>Press <strong>＋</strong> beside TRACKS to add a track.</li><li>Select a track or clip to inspect its properties.</li><li><strong>New clip</strong> creates a one-bar clip in the first free slot. You can also double-click an empty lane.</li><li>Drag a clip horizontally to move it with bar snap. An occupied position turns red and is rejected.</li><li><strong>Duplicate</strong> copies the clip and notes; <strong>Delete</strong> removes it. Undo is not available yet.</li></ul><p>Clips must stay inside the project and cannot overlap on the same track.</p></section>
      <section><h3>Instruments and mixing</h3><p>Select a track to open its mixer. Its controls remain visible when a clip is also selected.</p><ul><li><strong>Instrument</strong> chooses one of nine browser-synthesized presets with no samples or recordings.</li><li><strong>Volume</strong> runs from 0 to 100%. <strong>Pan</strong> moves between left (L), center (C) and right (R).</li><li><strong>Mute</strong> silences that track. <strong>Solo</strong> excludes tracks that are not soloed; several tracks can be soloed.</li><li>Every mixer change takes effect during playback without returning to the beginning.</li></ul><p>Piano Roll audition uses the track instrument, volume and pan, but bypasses Mute/Solo so it remains audible while you edit.</p></section>
      <section><h3>Keyboard shortcuts</h3><p>Select a clip in the Arranger. Shortcuts do not apply while typing in a field.</p><dl class="help-shortcuts"><div><dt><kbd>Space</kbd></dt><dd>Toggle Play and Pause in the workspace.</dd></div><div><dt><kbd>←</kbd> / <kbd>→</kbd></dt><dd>Move the clip by one bar.</dd></div><div><dt><kbd>Ctrl</kbd> + <kbd>D</kbd></dt><dd>Duplicate the clip. On Mac: Cmd + D.</dd></div><div><dt><kbd>Delete</kbd> / <kbd>Backspace</kbd></dt><dd>Delete the selected clip.</dd></div><div><dt><kbd>Esc</kbd></dt><dd>Cancel a drag or close this guide.</dd></div><div><dt><kbd>Tab</kbd></dt><dd>Move through controls; Enter activates the focused control.</dd></div></dl></section>
      <section><h3>Piano Roll: compose inside a clip</h3><p>The combined view opens by default with <strong>First Pattern</strong>. The adjacent <strong>Arranger</strong> and <strong>Piano Roll</strong> controls show which panel has focus without hiding the other. If you close the editor, double-click a clip, or select it and press <strong>Piano Roll</strong>, to open it again. It docks below the Arranger so both remain visible with the top transport. Drag the horizontal divider to redistribute their height; the vertical divider between Tracks and Arranger changes their width. Both also respond to arrow keys when focused and keep their position for the session. <strong>Expand</strong> gives the workspace to the editor; <strong>Restore</strong> returns to the combined view and <strong>Close</strong> hides it.</p><ul><li>The keyboard labels only octave Cs (C1, C2…). Black keys continue across the grid with subtle shading. Press any key to audition it.</li><li><strong>Draw</strong> creates notes; <strong>Select</strong> moves them and resizes from the right edge; <strong>Erase</strong> removes them.</li><li>Dragging vertically auditions every new semitone reached. Horizontal movement and resizing do not retrigger audition.</li><li><strong>Snap</strong> offers 1/4–1/32. Zoom changes horizontal scale. The form edits MIDI, start, duration and velocity.</li><li>With a note focused: horizontal arrows move one snap step, vertical arrows move one semitone and Delete/Backspace removes it.</li></ul><p>Editing notes stops playback; press Play to hear the result.</p></section>
      <section><h3>What to try now</h3><p>Press Play to hear both bars of First Pattern, then change a note while keeping the clip visible in the Arranger. Try Expand, Restore and Close; then create a second track and mix different instruments.</p></section>
    </div>
  `);
  document.body.append(dialog);
  let returnFocus: HTMLElement = button;
  button.setAttribute('aria-haspopup', 'dialog');
  button.addEventListener('click', () => {
    returnFocus = document.activeElement instanceof HTMLElement ? document.activeElement : button;
    if (!dialog.open) dialog.showModal();
  });
  dialog.querySelector('[data-close-help]')?.addEventListener('click', () => dialog.close());
  dialog.addEventListener('close', () => (returnFocus.isConnected ? returnFocus : button).focus({ preventScroll: true }));
}
